export const SET_USER_NAME = 'SET_USER_NAME';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCES';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOAD_MEETUP_SUCCES = 'LOAD_MEETUP_SUCCES';
export const SAVE_MEETUP_SUCCES = 'SAVE_MEETUP_SUCCES';
